examples/celery_progress_demo/celery_progress_demo/urls.py
from django.contrib import admin
from django.urls import path, include

from download import urls as download_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # Demo app
    path('', include(download_urls)),
    # Celery progress
    path('celery-progress/', include('celery_progress.urls')),
]

examples/celery_progress_demo/download/urls.py
from django.urls import path
# Demo view
from .views import demo_view

app_name = 'download'

urlpatterns = [
    # Demo view
    path('', demo_view, name='demo'),
]

examples/celery_progress_demo/download/models.py
from django.db import models

# Create your models here.

examples/celery_progress_demo/download/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .tasks import process_download
from django.views.decorators.http import require_http_methods
from celery.result import AsyncResult


task_id = {}


def demo_view(request: HttpRequest) -> HttpResponse:
    username = str(request.user.username)
    if request.method == 'POST':
        # Create Task
        download_task = process_download.delay()
        # Get ID
        task_id[username] = download_task.task_id
        # Print Task ID
        print(f'Celery Task ID: {task_id[username]}')
        # Return demo view with Task ID
        return render(request, 'progress.html', {'task_id': task_id[username]})
    else:
        # Return demo view
        return render(request, 'progress.html', {})

examples/celery_progress_demo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Celery Progress Demo</title>
        <meta name="Celery Progress Demo" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Bootstrap CSS -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    </head>

    <body>
        {% block demo %}{% endblock %}
        <!-- JQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <!-- Bootstrap JS -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <!-- Celery Progress -->
        <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
        
        {% block progress_bar_js %}{% endblock progress_bar_js %}
    </body>
</html>

examples/celery_progress_demo/templates/download.html
{% extends "base.html" %}
{% load static %}

{% block demo %}
<!-- Reset Form -->
<a href="{% url 'download:demo' %}" role="button" class="btn btn-primary btn-lg btn-block" style="border-radius: 0px;"><b>RESET</b></a>

<!-- Download Form -->
<div class="container text-center" style="padding-top: 20px;">
    <form action="{% url 'download:demo' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit" style="width:120px;">
            <strong>Download</strong>
        </button>
    </form>
</div>

<!-- Download Status -->
<div class="container" style="padding-top: 20px;">
    <div class="card" style="height: 120px;">
        {% block progress %}{% endblock progress %}
    </div>
</div>
{% endblock %}

examples/celery_progress_demo/templates/progress.html
{% extends "download.html" %}
{% load static %}
{% block progress %}
<div class="text-center" style="font-size: 14px">
    <div id="progress-bar-message">
    Click the "Download" button
    </div>
</div>
<div class='progress-wrapper' style="padding-top: 10px;">
  <div id='progress-bar' class='progress-bar progress-bar-striped' role='progressbar' style="height:30px; width: 0%; border-radius: 5px">&nbsp;</div>
</div>
<div id="celery-result">
</div>
{% endblock progress %}

{% block progress_bar_js %}
{% if task_id %}
<script type="text/javascript">
    // Progress Bar (JQuery)
    $(function () {
        var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
        CeleryProgressBar.initProgressBar(progressUrl, {})
    });
</script>
{% endif %}
{% endblock progress_bar_js %}